#!/bin/bash

#PBS -N stream
#PBS -M hyschive@phys.ntu.edu.tw
#PBS -m abe
#PBS -q workq
#PBS -k n
#PBS -l walltime=720:00:00
#PBS -l nodes=4:ppn=6
##PBS -o stdout
##PBS -e stderr
##PBS -W depend=afterok:JOB_ID

cd $PBS_O_WORKDIR

## for openmpi-1.6.0
mpirun -np 24 -npernode 6 ./gamer 1>>log 2>&1

## for openmpi-1.4.3-qlc
#mpirun -np 32 -npernode 2 -hostfile $PBS_NODEFILE -bind-to-socket ./gamer 1>>log 2>&1

## script to restart a simulation automatically if the run failed
## sh auto_restart.sh 1>>stdout 2>>stderr
